### ISSUE TITLE
Feature / Collaboration?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [f-bn/lxd-images#3]
https://github.com/pieroproietti/penguins-eggs

https://penguins-eggs.net/

1] 

Would it be possible to package these custom containers / vms into ISO images?

2]

Would it be possible do the following, use btrfs/rsync to;...

2-A] 

Take a "snapshot" of the running hostfs "filesystem" and send it to or create a temporary/permanent 'users choice' "custom container".

2-B]

Make development containers of the running hostfs on-demand & by cron jobs & other types of jobs & requests.

3] 

Do you have any graphical front-end planned?

I have found this a while ago, maybe you could fork/clone it, upstream it for Qt/Plasma & GTK/Gnome & modify the the UI to fit the needs of your repo/tool.

https://github.com/marbetschar/tins

**Comment by f-bn** [comment]
Hello,

Sorry for the response delay. Regarding your questions, as mentioned [here](https://github.com/automaticserver/lxe/issues/26), this repository simply containing manifests to build LXD images with the official tool from the LXD team. (Distrobuilder) to build them. You can build them on your own using these manifests or the ones from the LXC team : [https://github.com/lxc/lxc-ci](https://github.com/lxc/lxc-ci)

The produced images are more or less the same you can find here : [https://images.linuxcontainers.org/](https://images.linuxcontainers.org/)

I'll close this issue since I can't help you here.

Regards
